version: '2'
services:
    mysql:
        image: mysql:5.7
        container_name: db-patchmanagement-chocoinfo-mysql-001
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: da8xun789a7xd897w7897x89d7s8a7
          MYSQL_DATABASE: db_chocoinfo
          MYSQL_USER: db_chocoinfo
          MYSQL_PASSWORD: db_chocoinfoc28r792347cr589 
        volumes:
          - ./storage/mysql:/var/lib/mysql
    web:
         build: ./web
         container_name: api-patchmanagement-chocoinfo-lumen-001
         ports:
             - 10000:80
         volumes:
             - ./web:/var/www
             - ./storage/app:/var/www/storage/app
             - ./storage/logs:/var/www/storage/logs